import { execFileSync } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type OpenApiSpec = {
  openapi: string;
  info?: { title?: string; version?: string };
  servers?: Array<{ url: string }>;
  paths: Record<string, PathItem>;
  components?: { schemas?: Record<string, unknown> };
};

type PathItem = Record<string, Operation | undefined>;

type Operation = {
  operationId?: string;
  tags?: string[];
  summary?: string;
  description?: string;
  parameters?: Parameter[];
  requestBody?: {
    required?: boolean;
    content?: Record<string, { schema?: unknown }>;
  };
  responses?: Record<string, ResponseObject>;
};

type ResponseObject = {
  content?: Record<string, { schema?: unknown }>;
};

type Parameter = {
  name: string;
  in: "path" | "query" | "header" | "cookie";
  required?: boolean;
  description?: string;
  schema?: unknown;
};

const methods = ["get", "put", "post", "delete", "patch", "options", "head"];
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const specs = [
  {
    version: "v1",
    source: "https://apidocs.myworkboard.com/openapi.json",
    specPath: "packages/core/openapi/workboard-v1.openapi.json",
    apiSpecPath: "packages/core/openapi/workboard-v1.api.openapi.json",
    typesPath: "packages/core/src/workboard/generated/v1.ts",
    apiIdentifier: "workboard-v1",
    sdkPath: ".api/apis/workboard-v1/index.ts",
  },
  {
    version: "v2",
    source: "https://www.myworkboard.com/wb/apis/v2/docs-json",
    specPath: "packages/core/openapi/workboard-v2.openapi.json",
    apiSpecPath: "packages/core/openapi/workboard-v2.api.openapi.json",
    typesPath: "packages/core/src/workboard/generated/v2.ts",
    apiIdentifier: "workboard-v2",
    sdkPath: ".api/apis/workboard-v2/index.ts",
  },
] as const;

async function main() {
  const operations = [];

  for (const specConfig of specs) {
    const response = await fetch(specConfig.source);
    if (!response.ok) {
      throw new Error(
        `Failed to fetch ${specConfig.source}: ${response.status} ${response.statusText}`,
      );
    }

    const spec = (await response.json()) as OpenApiSpec;
    const apiSpec = sanitizeOpenApiForApiGenerator(spec) as OpenApiSpec;
    await fs.writeFile(
      path.join(root, specConfig.specPath),
      `${JSON.stringify(spec, null, 2)}\n`,
    );
    await fs.writeFile(
      path.join(root, specConfig.apiSpecPath),
      `${JSON.stringify(apiSpec, null, 2)}\n`,
    );

    await removeExistingSdk(specConfig.apiIdentifier);

    execFileSync(
      "npx",
      [
        "openapi-typescript",
        specConfig.specPath,
        "-o",
        specConfig.typesPath,
      ],
      { cwd: root, stdio: "inherit" },
    );

    execFileSync(
      "npx",
      [
        "api",
        "install",
        specConfig.apiSpecPath,
        "--identifier",
        specConfig.apiIdentifier,
        "--lang",
        "ts",
        "--yes",
      ],
      {
        cwd: root,
        env: { ...process.env, npm_config_legacy_peer_deps: "true" },
        stdio: "inherit",
      },
    );

    const sdkMethodMap = await parseSdkMethodMap(specConfig.sdkPath);
    operations.push(...collectOperations(specConfig.version, apiSpec, sdkMethodMap));
  }

  const generated = `// Generated by packages/scripts/src/generate-workboard.ts\n` +
    `// Do not edit by hand.\n\n` +
    `import type { WorkboardOperation } from "./types";\n\n` +
    `export const workboardOperations = ${JSON.stringify(
      operations,
      null,
      2,
    )} as const satisfies readonly WorkboardOperation[];\n`;

  await fs.writeFile(
    path.join(root, "packages/core/src/workboard/operations.ts"),
    generated,
  );
  await removeGeneratedSdkNodeModules();
  console.log(`Generated ${operations.length} Workboard MCP operations.`);
}

function collectOperations(
  version: "v1" | "v2",
  spec: OpenApiSpec,
  sdkMethodMap: Map<string, string>,
) {
  const operations = [];
  const seen = new Set<string>();

  for (const [openApiPath, pathItem] of Object.entries(spec.paths)) {
    for (const method of methods) {
      const operation = pathItem[method];
      if (!operation) continue;

      const name = uniqueName(
        makeToolName(version, method, openApiPath, operation),
        seen,
      );
      const inputSchema = buildInputSchema(spec, operation);
      const readOnly = method === "get" || method === "head" || method === "options";
      const destructive =
        method === "delete" ||
        method === "patch" ||
        method === "put" ||
        /\b(delete|deactivate|disable|clear|remove|revoke)\b/i.test(
          operation.summary ?? "",
        );

      operations.push({
        name,
        version,
        method: method.toUpperCase(),
        path: openApiPath,
        title: titleFromOperation(operation, method, openApiPath),
        description: descriptionFromOperation(operation, method, openApiPath),
        tags: operation.tags ?? [],
        requiredScope: readOnly ? "workboard:read" : "workboard:write",
        contentType: requestContentType(operation),
        sdkMethodName: sdkMethodMap.get(`${method.toUpperCase()} ${openApiPath}`),
        inputSchema,
        outputSchema: buildOutputSchema(spec, operation),
        annotations: {
          title: titleFromOperation(operation, method, openApiPath),
          readOnlyHint: readOnly,
          destructiveHint: destructive,
          idempotentHint:
            method === "get" || method === "head" || method === "put" || method === "delete",
          openWorldHint: true,
        },
      });
    }
  }

  return operations;
}

function buildOutputSchema(spec: OpenApiSpec, operation: Operation) {
  const response = successResponse(operation);
  const schema = response ? responseBodySchema(response) : undefined;
  if (!schema) {
    return {
      type: "object",
      additionalProperties: false,
      properties: {},
    };
  }

  return normalizeOutputSchema(dereference(spec, schema));
}

function successResponse(operation: Operation) {
  const responses = operation.responses ?? {};

  for (const status of ["200", "201", "202", "204", "default"]) {
    if (responses[status]) return responses[status];
  }

  const successStatus = Object.keys(responses)
    .filter((status) => /^2\d\d$/.test(status))
    .sort()[0];

  return successStatus ? responses[successStatus] : undefined;
}

function responseBodySchema(response: ResponseObject) {
  const content = response.content;
  if (!content) return undefined;
  return (
    content["application/json"]?.schema ??
    content["application/problem+json"]?.schema ??
    Object.values(content)[0]?.schema
  );
}

function normalizeOutputSchema(schema: unknown): unknown {
  const normalized = allowAdditionalOutputProperties(schema);
  const record = objectSchemaRecord(normalized);
  const schemaType = Array.isArray(record.type) ? record.type[0] : record.type;

  if (
    schemaType === "object" ||
    record.properties ||
    record.oneOf ||
    record.anyOf ||
    record.allOf
  ) {
    return record;
  }

  return {
    type: "object",
    additionalProperties: false,
    properties: {
      data: record,
    },
  };
}

function allowAdditionalOutputProperties(schema: unknown): unknown {
  if (Array.isArray(schema)) {
    return schema.map((item) => allowAdditionalOutputProperties(item));
  }

  if (!schema || typeof schema !== "object") return schema;

  const record = schema as Record<string, unknown>;
  const copy: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    copy[key] = allowAdditionalOutputProperties(value);
  }

  const schemaType = Array.isArray(copy.type) ? copy.type[0] : copy.type;
  if (schemaType === "object" || copy.properties) {
    copy.type = "object";
    copy.additionalProperties = true;
  }

  return copy;
}

function buildInputSchema(spec: OpenApiSpec, operation: Operation) {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];
  const grouped: Record<string, { required?: string[] } | undefined> = {
    path: parametersToSchema(spec, operation, "path"),
    query: parametersToSchema(spec, operation, "query"),
    headers: parametersToSchema(spec, operation, "header"),
  };

  for (const [key, schema] of Object.entries(grouped)) {
    if (!schema) continue;
    properties[key] = schema;
    if (schema.required?.length) required.push(key);
  }

  const contentType = requestContentType(operation);
  const bodySchema = contentType
    ? operation.requestBody?.content?.[contentType]?.schema
    : undefined;
  if (bodySchema) {
    properties.body = dereference(spec, bodySchema);
    if (operation.requestBody?.required) required.push("body");
  }

  return {
    type: "object",
    additionalProperties: false,
    properties,
    ...(required.length ? { required } : {}),
  };
}

function parametersToSchema(
  spec: OpenApiSpec,
  operation: Operation,
  location: Parameter["in"],
) {
  const parameters = (operation.parameters ?? []).filter(
    (parameter) =>
      parameter.in === location &&
      parameter.name.toLowerCase() !== "authorization" &&
      parameter.name.toLowerCase() !== "content-type",
  );
  if (parameters.length === 0) return undefined;

  const required = parameters
    .filter((parameter) => parameter.required)
    .map((parameter) => parameter.name);
  const properties = Object.fromEntries(
    parameters.map((parameter) => [
      parameter.name,
      {
        ...objectSchemaRecord(
          dereference(spec, parameter.schema ?? { type: "string" }),
        ),
        ...(parameter.description ? { description: parameter.description } : {}),
      },
    ]),
  );

  return {
    type: "object",
    additionalProperties: false,
    properties,
    ...(required.length ? { required } : {}),
  };
}

function dereference(spec: OpenApiSpec, schema: unknown, seen = new Set<string>()): unknown {
  if (!schema || typeof schema !== "object") return schema ?? {};
  const record = schema as Record<string, unknown>;
  const ref = record.$ref;

  if (typeof ref === "string") {
    if (seen.has(ref)) return {};
    seen.add(ref);
    const prefix = "#/components/schemas/";
    if (ref.startsWith(prefix)) {
      return dereference(spec, spec.components?.schemas?.[ref.slice(prefix.length)], seen);
    }
    return {};
  }

  if (Array.isArray(schema)) {
    return schema.map((item) => dereference(spec, item, new Set(seen)));
  }

  const copy: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    copy[key] = dereference(spec, value, new Set(seen));
  }
  return copy;
}

function objectSchemaRecord(value: unknown) {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : { type: "string" };
}

function requestContentType(operation: Operation) {
  const content = operation.requestBody?.content;
  if (!content) return undefined;
  if (content["application/json"]) return "application/json";
  return Object.keys(content)[0];
}

function makeToolName(
  version: "v1" | "v2",
  method: string,
  openApiPath: string,
  operation: Operation,
) {
  if (operation.operationId) {
    return normalizeName(
      `workboard_${version}_${operation.operationId.replace(/Controller_/g, "")}`,
    );
  }

  const pathPart = openApiPath
    .split("/")
    .filter(Boolean)
    .map((part) => {
      const match = part.match(/^\{(.+)\}$/);
      return match ? `by_${match[1]}` : part;
    })
    .join("_");

  return normalizeName(`workboard_${version}_${method}_${pathPart || "root"}`);
}

function uniqueName(name: string, seen: Set<string>) {
  let candidate = name;
  let index = 2;
  while (seen.has(candidate)) {
    candidate = `${name}_${index}`;
    index += 1;
  }
  seen.add(candidate);
  return candidate;
}

function normalizeName(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9_-]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .toLowerCase();
}

function titleFromOperation(operation: Operation, method: string, openApiPath: string) {
  return operation.summary?.replace(/[`*_]/g, "") ?? `${method.toUpperCase()} ${openApiPath}`;
}

function descriptionFromOperation(
  operation: Operation,
  method: string,
  openApiPath: string,
) {
  const pieces = [
    `${method.toUpperCase()} ${openApiPath}`,
    operation.summary,
    stripHtml(operation.description),
  ].filter(Boolean);

  return pieces.join("\n\n");
}

function stripHtml(value: string | undefined) {
  return value
    ?.replace(/<[^>]*>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function sanitizeOpenApiForApiGenerator(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => sanitizeOpenApiForApiGenerator(item));
  }

  if (!value || typeof value !== "object") return value;

  const record = value as Record<string, unknown>;
  if (record.type === "null") return { nullable: true };

  const copy: Record<string, unknown> = {};
  for (const [key, child] of Object.entries(record)) {
    copy[key] = sanitizeOpenApiForApiGenerator(child);
  }

  for (const key of ["oneOf", "anyOf"]) {
    const original = record[key];
    if (!Array.isArray(original)) continue;

    const filtered = original.filter((item) => !isNullSchema(item));
    if (filtered.length !== original.length) {
      copy.nullable = true;
      if (filtered.length > 0) {
        copy[key] = filtered.map((item) => sanitizeOpenApiForApiGenerator(item));
      } else {
        delete copy[key];
      }
    }
  }

  if (Array.isArray(record.type) && record.type.includes("null")) {
    const types = record.type.filter((type) => type !== "null");
    copy.nullable = true;
    if (types.length === 1) copy.type = types[0];
    else if (types.length > 1) copy.type = types;
    else delete copy.type;
  }

  return copy;
}

function isNullSchema(value: unknown) {
  return Boolean(value && typeof value === "object" && (value as { type?: unknown }).type === "null");
}

async function parseSdkMethodMap(sdkPath: string) {
  const source = await fs.readFile(path.join(root, sdkPath), "utf8");
  const map = new Map<string, string>();
  const methodRegex =
    /^\s{2}([A-Za-z0-9_]+)\([^)]*\):[^{]+\{\s*return this\.core\.fetch\('([^']+)', '([^']+)'/gm;
  let match: RegExpExecArray | null;

  while ((match = methodRegex.exec(source))) {
    const [, sdkMethodName, openApiPath, method] = match;
    map.set(`${method.toUpperCase()} ${openApiPath}`, sdkMethodName);
  }

  return map;
}

async function removeExistingSdk(apiIdentifier: string) {
  await fs.rm(path.join(root, ".api/apis", apiIdentifier), {
    force: true,
    recursive: true,
  });

  const apiJsonPath = path.join(root, ".api/api.json");
  try {
    const apiJson = JSON.parse(await fs.readFile(apiJsonPath, "utf8")) as {
      version: string;
      apis?: Array<{ identifier?: string }>;
    };
    apiJson.apis = (apiJson.apis ?? []).filter(
      (api) => api.identifier !== apiIdentifier,
    );
    await fs.writeFile(apiJsonPath, `${JSON.stringify(apiJson, null, 2)}\n`);
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code !== "ENOENT") throw error;
  }
}

async function removeGeneratedSdkNodeModules() {
  await Promise.all(
    specs.map((specConfig) =>
      fs.rm(path.join(root, ".api/apis", specConfig.apiIdentifier, "node_modules"), {
        force: true,
        recursive: true,
      }),
    ),
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
